//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocSPBBot.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PocSPBBot.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;opération refusée est-elle.
        /// </summary>
        internal static string BOT_PROMPT_CARD_ISSUE {
            get {
                return ResourceManager.GetString("BOT_PROMPT_CARD_ISSUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un paiement.
        /// </summary>
        internal static string BOT_PROMPT_CARD_ISSUE_PAYMENT {
            get {
                return ResourceManager.GetString("BOT_PROMPT_CARD_ISSUE_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un retrait.
        /// </summary>
        internal static string BOT_PROMPT_CARD_ISSUE_WITHDRAWAL {
            get {
                return ResourceManager.GetString("BOT_PROMPT_CARD_ISSUE_WITHDRAWAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous confirmez votre choix ?.
        /// </summary>
        internal static string BOT_PROMPT_CONFIRM_CHOICE {
            get {
                return ResourceManager.GetString("BOT_PROMPT_CONFIRM_CHOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce choix n&apos;est pas valide.
        /// </summary>
        internal static string BOT_PROMPT_CONFIRM_WRONG_CHOICE {
            get {
                return ResourceManager.GetString("BOT_PROMPT_CONFIRM_WRONG_CHOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avec quel moyen de paiement vous avez un problème ?.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avec votre carte bleue.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_CARD {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de chèque.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_CHEQUE {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_CHEQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de virement.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_TRANSFER {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;agit-il d&apos;un retrait .
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A l&apos;étranger.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_ABROAD {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_ABROAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestique.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_DOMESTIC {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_DOMESTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quel nouveau plafond souhaitez-vous ?.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_NEW_THRESHOLD {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_NEW_THRESHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non je veux contacter mon conseiller.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_NO_INCREASE_CALL_CONS {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_NO_INCREASE_CALL_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appel en cours de votre conseiller....
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_NO_THRESHOLD {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_NO_THRESHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avez-vous essayé dans d&apos;autres DAB ou d&apos;autres établissements ?.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous allez entrer en relation avec votre conseiller.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM_CALLING_CONS {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM_CALLING_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il se peut qu&apos;il s&apos;agisse d&apos;un dysfonctionnement de votre carte. Nous vous suggérons de commander une nouvelle carte. Voulez-vous commander une nouvelle carte ou contacter votre conseiller ?.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM_CARD_KO {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM_CARD_KO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je veux contacter mon conseiller.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM_CONTACT_CONS {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM_CONTACT_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM_NO {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je veux commander une nouvelle carte.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM_ORDER_NEW_CARD {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM_ORDER_NEW_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM_YES {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_OTHER_ATM_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui je veux augmenter mon plafond.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_YES_INCREASE {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_YES_INCREASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez atteind votre plafond de retrait domestique. Voulez vous l&apos;augmenter ?.
        /// </summary>
        internal static string BOT_PROMPT_ISSUE_WITHDRAWAL_YESNO {
            get {
                return ResourceManager.GetString("BOT_PROMPT_ISSUE_WITHDRAWAL_YESNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé j&apos;ai du mal à comprendre : Votre agence la plus proche se trouve (Geolocalisation).
        /// </summary>
        internal static string BOT_PROMPT_TOO_MANY_TRY {
            get {
                return ResourceManager.GetString("BOT_PROMPT_TOO_MANY_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce choix ne fait pas partie d&apos;un choix valide.
        /// </summary>
        internal static string BOT_PROMPT_TRY_AGAIN_CHOOSE_ISSUE {
            get {
                return ResourceManager.GetString("BOT_PROMPT_TRY_AGAIN_CHOOSE_ISSUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour je suis un bot, à votre service.
        /// </summary>
        internal static string BOT_WELCOME {
            get {
                return ResourceManager.GetString("BOT_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue dans le résolveur de problème de carte bleue.
        /// </summary>
        internal static string DBG_CARD_RESOLVER {
            get {
                return ResourceManager.GetString("DBG_CARD_RESOLVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur dans le numéro de carte bleue.
        /// </summary>
        internal static string ERROR_DEBUG_SOMETHING_WRONG_WITH_CARD {
            get {
                return ResourceManager.GetString("ERROR_DEBUG_SOMETHING_WRONG_WITH_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous allons désormais procéder à votre authentification.
        /// </summary>
        internal static string USER_DLG_AUTHENTICATION {
            get {
                return ResourceManager.GetString("USER_DLG_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette réponse est erronnée.
        /// </summary>
        internal static string USER_DLG_AUTHENTICATION_WRONG_ANSWER {
            get {
                return ResourceManager.GetString("USER_DLG_AUTHENTICATION_WRONG_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je reviens au début.....
        /// </summary>
        internal static string USER_DLG_BACK_TO_START {
            get {
                return ResourceManager.GetString("USER_DLG_BACK_TO_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quels sont les numéros de votre carte ?.
        /// </summary>
        internal static string USER_DLG_CARD_NUMBER {
            get {
                return ResourceManager.GetString("USER_DLG_CARD_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérification de vos informations .....
        /// </summary>
        internal static string USER_DLG_CHECKING_AUTHENTICATION {
            get {
                return ResourceManager.GetString("USER_DLG_CHECKING_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre carte est bloquée, veuillez contacter votre conseiller..
        /// </summary>
        internal static string USER_DLG_CHECKING_CARD_BLOCKED {
            get {
                return ResourceManager.GetString("USER_DLG_CHECKING_CARD_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de carte erroné, veuillez contacter votre conseiller..
        /// </summary>
        internal static string USER_DLG_CHECKING_CARD_KO {
            get {
                return ResourceManager.GetString("USER_DLG_CHECKING_CARD_KO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérification du numéros de votre carte en cours ....
        /// </summary>
        internal static string USER_DLG_CHECKING_CARD_NUMBER {
            get {
                return ResourceManager.GetString("USER_DLG_CHECKING_CARD_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez dépassé votre montant de découvert. Veuillez contacter votre conseiller..
        /// </summary>
        internal static string USER_DLG_CHECKING_CARD_OVERDRAFT {
            get {
                return ResourceManager.GetString("USER_DLG_CHECKING_CARD_OVERDRAFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérification de votre demande en cours.....
        /// </summary>
        internal static string USER_DLG_CHECKING_WITHDRAWAL {
            get {
                return ResourceManager.GetString("USER_DLG_CHECKING_WITHDRAWAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre nouvelle carte est commandée. Merci de votre confiance. A bientôt.
        /// </summary>
        internal static string USER_DLG_NEW_CARD_ORDERED {
            get {
                return ResourceManager.GetString("USER_DLG_NEW_CARD_ORDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre plafond a bien été modifié, merci et à bientôt.
        /// </summary>
        internal static string USER_DLG_NEW_THRESHOLD_ACCEPTED {
            get {
                return ResourceManager.GetString("USER_DLG_NEW_THRESHOLD_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonction non implementée.
        /// </summary>
        internal static string USER_DLG_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("USER_DLG_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plafond non autorisé (max 150).
        /// </summary>
        internal static string USER_DLG_THRESHOLD_TO_HIGH {
            get {
                return ResourceManager.GetString("USER_DLG_THRESHOLD_TO_HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWWWW.
        /// </summary>
        internal static string WWWWW {
            get {
                return ResourceManager.GetString("WWWWW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé je ne peux rien faire pour une carte bloquée. Pouvez-vous contacter votre conseiller ?.
        /// </summary>
        internal static string Z_COG_BOT_CONTACT_YOUR_ADVISOR {
            get {
                return ResourceManager.GetString("Z_COG_BOT_CONTACT_YOUR_ADVISOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour, que puis-je faire pour vous ?.
        /// </summary>
        internal static string Z_COG_BOT_HOW_HELP_YOU {
            get {
                return ResourceManager.GetString("Z_COG_BOT_HOW_HELP_YOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, je n&apos;ai pas appris votre langue seriez vous parler en Français, En Anglais ? Merci.
        /// </summary>
        internal static string Z_COG_BOT_LANGUAGE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("Z_COG_BOT_LANGUAGE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé je n&apos;ai pas compris, pourriez-vous recommencer ?.
        /// </summary>
        internal static string Z_COG_BOT_LUIS_NOT_UNDERSTAND_LEVEL_1 {
            get {
                return ResourceManager.GetString("Z_COG_BOT_LUIS_NOT_UNDERSTAND_LEVEL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous me voyez navré mais je n&apos;ai pas compris, auriez-vous l&apos;obligeance de recommencer ?.
        /// </summary>
        internal static string Z_COG_BOT_LUIS_NOT_UNDERSTAND_LEVEL_2 {
            get {
                return ResourceManager.GetString("Z_COG_BOT_LUIS_NOT_UNDERSTAND_LEVEL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je suis un bot à votre service.
        /// </summary>
        internal static string Z_COG_BOT_WELCOME {
            get {
                return ResourceManager.GetString("Z_COG_BOT_WELCOME", resourceCulture);
            }
        }
    }
}
